### ISSUE TITLE
ES6 Suport

### ISSUE THREAD

**Issue by david2tm** [kwonoj/cld3-asm#143]
I have been using this lib with Webpack, and stuff worked.
Now I'm trying to move to Vite -- and have "issues" :)

Mainly it comes from the way how emscripten Modularize is expored.

I've seen the emscripten have a flag EXPORT_ES6 ([but it's not mentioned in the docs, for some reason](https://github.com/emscripten-core/emscripten/issues/14383)) which solves the problem.

eg uses `export default Module` instead.

I think the fix is easy in [this repos](https://github.com/kwonoj/docker-cld3-wasm/blob/4d0870c3dd57be5b4ef32ec3915e0627b2717aaf/build/build.sh#L37) build.sh, just add `-s EXPORT_ES6=1 \`

**Comment by kwonoj** [comment]
Per the linked issue it looks like changing output to esm, which likely causr a breaking changes to cjs usage. If you experience with the other bundler, sugges to check with bundler config first and if you are confident it is coming from this library itself, please share detail. I cannot able to understand what issue you are experiencing by reading this report.
